drop table if exists type_de_vaccin_tranche_dage_et_departement;
CREATE TABLE type_de_vaccin_tranche_dage_et_departement (
    id INT,
    date_reference DATE,
    semaine_injection VARCHAR(255),
    region_residence VARCHAR(255),
    libelle_region VARCHAR(255),
    departement_residence VARCHAR(255),
    libelle_departement VARCHAR(255),
    population_insee VARCHAR(255),
    classe_age VARCHAR(255),
    libelle_classe_age VARCHAR(255),
    type_vaccin VARCHAR(255),
    effectif_1_inj VARCHAR(255),
    effectif_termine VARCHAR(255),
    effectif_cumu_1_inj VARCHAR(255),
    effectif_cumu_termine VARCHAR(255),
    taux_1_inj VARCHAR(255), 
    taux_termine VARCHAR(255), 
    taux_cumu_1_inj VARCHAR(255), 
    taux_cumu_termine VARCHAR(255),
    date DATE,
    effectif_rappel VARCHAR(255),
    effectif_cumu_rappel VARCHAR(255),
    effectif_rappel_parmi_eligible VARCHAR(255),
    effectif_eligible_au_rappel VARCHAR(255),
    taux_rappel VARCHAR(255),
    taux_cumu_rappel VARCHAR(255),
    taux_cumu_rappeleli VARCHAR(255)
    ,execution_date DATE
);
