CREATE TABLE if not exists vaccination_centers (
    id INT,
    gid INTEGER,
    nom TEXT,
    arrete_pref_numero TEXT,
    xy_precis TEXT,
    id_adr TEXT,
    adr_num TEXT,
    adr_voie TEXT,
    com_cp TEXT,
    com_insee TEXT,
    com_nom TEXT,
    lat_coor1 NUMERIC,
    long_coor1 NUMERIC,
    structure_siren TEXT,
    structure_type TEXT,
    structure_rais TEXT,
    structure_num TEXT,
    structure_voie TEXT,
    structure_cp TEXT,
    structure_insee TEXT,
    structure_com TEXT,
    _userid_creation TEXT,
    _userid_modification TEXT,
    _edit_datemaj TIMESTAMP,
    lieu_accessibilite TEXT,
    rdv_lundi TEXT,
    rdv_mardi TEXT,
    rdv_mercredi TEXT,
    rdv_jeudi TEXT,
    rdv_vendredi TEXT,
    rdv_samedi TEXT,
    rdv_dimanche TEXT,
    rdv TEXT,
    date_fermeture DATE,
    date_ouverture DATE,
    rdv_site_web TEXT,
    rdv_tel TEXT,
    rdv_tel2 TEXT,
    rdv_modalites TEXT,
    rdv_consultation_prevaccination TEXT,
    centre_svi_repondeur TEXT,
    centre_fermeture TEXT,
    reserve_professionels_sante BOOLEAN,
    centre_type TEXT
);
CREATE INDEX if not exists vaccination_centers_index
ON vaccination_centers (gid, com_cp,date_fermeture,date_ouverture);